# Example Zone and Record pair which can be used for testing the
# route53 provider. Note that you must change the domainNames to
# match those of your hosted zone!
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
  - records:
    - pattern: "*.example.org."
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-example-org
spec:
  domainName: www.example.org.
  type: A
  rdata: "192.168.0.1"
